title: StockCast News
email: stockcast.app@gmail.com
description: >-
  StockCast News - Notícias e análise de empresas listadas na bolsa de valores - B3.
baseurl: ""
url: "https://news.stockcast.com.br"
urlBlog: "https://news.stockcast.com.br"

posthog_api_key: "phc_CLVTopIBYCwPZnuVerKJCvHvA8hYlCAikBiKBJPlPpL"

theme: 

plugins:
  - jekyll-feed

include:
  - assets/css

sass:
  sass_dir: assets/css
  style: compressed
